// Bookshelf
export const SET_SEARCHED_BOOKSHELVES = 'SET_SEARCHED_BOOKSHELVES'

// Navigation
export const SET_TAB = 'SET_TAB'
export const NAV_RESET = 'NAV_RESET'

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAV_JUMP_TO_KEY = 'NAV_JUMP_TO_KEY'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'

//Alert
export const SET_ALERT_READER_OPTIONS = 'SET_ALERT_READER_OPTIONS'

//Reader
export const SET_DIRECTORY = 'SET_DIRECTORY'
export const SET_CHAPTER_DETAIL = 'SET_CHAPTER_DETAIL'
export const SET_NEXT_CHAPTER_DETAIL = 'SET_NEXT_CHAPTER_DETAIL'
export const SET_LAST_CHAPTER_DETAIL = 'SET_LAST_CHAPTER_DETAIL'
export const GET_FIRST_RENDER_CHAPTER = 'GET_FIRST_RENDER_CHAPTER'

//Search
export const SET_SEARCH_NOVEL_LIST = 'SET_SEARCH_NOVEL_LIST'
export const SET_SEARCH_NOVEL_WORDS = 'SET_SEARCH_NOVEL_WORDS'
export const SET_SEARCH_NOVEL_INFO = 'SET_SEARCH_NOVEL_INFO'
export const SEND_IMG = 'SEND_IMG'
